# Generated by Django 5.0 on 2024-01-06 19:36

import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.recipe_directory_path),
        ),
    ]
