# Generated by Django 5.0 on 2024-01-07 12:01

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_author_alter_recipe_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRecipe',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=65, verbose_name='título')),
                ('description', models.CharField(max_length=165, verbose_name='descrição')),
                ('slug', models.SlugField()),
                ('preparation_time', models.IntegerField(verbose_name='tempo de preparo')),
                ('preparation_time_unit', models.CharField(max_length=65, verbose_name='unidade de medida')),
                ('servings', models.IntegerField(verbose_name='rendimento')),
                ('servings_unit', models.CharField(max_length=65, verbose_name='medida do rendimento')),
                ('preparation_steps', models.TextField(verbose_name='receita')),
                ('preparation_steps_is_html', models.BooleanField(default=False, verbose_name='receita em html?')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_published', models.BooleanField(default=False, verbose_name='publicado')),
                ('cover', models.TextField(blank=True, max_length=100, null=True, verbose_name='imagem')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='recipes.category', verbose_name='categoria')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical recipe',
                'verbose_name_plural': 'historical recipes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
