# Generated by Django 5.0 on 2024-01-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_historicalrecipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audit',
        ),
    ]
